from pathlib import Path
import json

root=Path(__file__).parent/'dist'
airbnb='https://www.airbnb.co.in/rooms/30969567'
nav=[('house','The House'),('stay','Stay'),('retreats','Retreats'),('hemp','Build With Hemp'),('story','Our Story'),('visit','Before You Come'),('gallery','Gallery')]
def photo(name,alt): return f'<img loading="lazy" src="/assets/{name}.jpg" alt="{alt}">'
def link(href,label,cls='button'): return f'<a class="{cls}" href="{href}">{label}</a>'
def section(kicker,title,text): return f'<section class="intro wrap"><p class="eyebrow">{kicker}</p><h2>{title}</h2><p>{text}</p></section>'
def cards(items): return '<div class="cards wrap">'+''.join(f'<article><span class="number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>' for i,(t,d) in enumerate(items))+'</div>'
booking=f'<section class="booking wrap"><p class="eyebrow">A LITTLE FURTHER. A LITTLE CLOSER TO YOURSELF.</p><h2>Your mountain pause<br>begins here.</h2><p>Choose your dates on Airbnb, or speak with us about a longer stay.</p>{link(airbnb,"Check availability on Airbnb ↗")}{link("/retreats/","Plan a retreat","text-link")}</section>'
pages={}
pages['']=('A Hemp Home in the Himalayas',f'''<section class="hero"><img src="/assets/house.jpg" alt="The Himalayan hemp house with local stone walls and rooftop solar panels" fetchpriority="high"><div class="hero-content"><p class="eyebrow">FALDAKOT MALLA · UTTARAKHAND</p><h1>A hemp home<br>in the <em>Himalayas.</em></h1><p>Come for the mountains.<br>Stay for a slower way of being.</p><div class="actions">{link('/stay/','Stay here')}{link('/retreats/','Host a retreat','button outline')}</div></div><span class="hero-note">STAY · CREATE · LEARN · RECONNECT</span></section>
<div class="material-bar">Built with hemp & lime <span>Local stone & timber</span><span>Powered by sunlight</span><span>Rooted in the Himalayas</span></div>
{section('A DIFFERENT KIND OF LUXURY','Space to breathe.<br>Time to simply be.','A quiet village home, a trail through the hills and days with room to unfold. Himalayan Hemp Eco Stay brings natural building and slow living together in the mountains of Uttarakhand.')}
<section class="split wrap"><div>{photo('room','Mountain landscape seen from the village')}<p class="caption">The landscape sets the pace.</p></div><div class="copy"><p class="eyebrow">A HOUSE WITH A PURPOSE</p><h2>Made of the earth.<br>Open to possibility.</h2><p>Hempcrete, lime, stone and timber give this home its character. Discover a living laboratory for natural building, creativity and a more thoughtful relationship with place.</p>{link('/house/','Explore the house →','text-link')}</div></section>
{cards([('Stay a little slower','Short escapes, unhurried residencies of 7–28 days, or time together in the whole house. Longer stays are arranged with the hosts.'),('Bring your people','Start a conversation about a small yoga, writing, art or research retreat, shaped around the house and your group.'),('Learn from the house','Look closer at hemp building, natural finishes and the material choices that make this place distinctive.')])}
<section class="journey"><div class="wrap"><p class="eyebrow">THE ARRIVAL IS PART OF THE STAY</p><h2>Leave the road.<br>Find your rhythm.</h2><div class="trail"><span>01 &nbsp; Roadhead</span><span>02 &nbsp; Trail</span><span>03 &nbsp; Village</span><span>04 &nbsp; Hemp house</span></div><p>Allow around an hour for the walk, depending on your route and pace. Limited shops, quiet evenings and a little preparation are part of life here.</p>{link('/visit/','Before you come →','text-link')}</div></section>
<section class="split wrap"><div class="copy"><p class="eyebrow">LIFE, AT A HUMAN PACE</p><h2>Make something.<br>Or make some space.</h2><p>Read, walk, observe local craft, or bring the project you have been meaning to begin. Ask us about experiences available during your visit.</p>{link('/retreats/','Retreats & residencies →','text-link')}</div>{photo('landscape','Guests learning traditional basket weaving')}</section>
<section class="reviews wrap"><p class="eyebrow">FROM THOSE WHO HAVE BEEN HERE</p><h2>Let our guests tell the story.</h2><p>Read guest experiences and the latest listing details before choosing your stay.</p>{link(airbnb,'Read reviews on Airbnb ↗','text-link')}</section>''')
pages['house']=('The House',section('NATURAL MATERIALS. EVERYDAY BEAUTY.','A home to inhabit,<br>not just a room to book.','Explore the rooms and shared spaces with the hosts before choosing your stay. The house combines traditional Himalayan materials with hemp-based construction.')+f'<div class="wide wrap">{photo("house","Exterior of the hemp house")}</div>'+cards([('The rooms','Ask about the Talla and Malla sleeping spaces, current bed configuration and bathroom arrangements.'),('Kitchen & gathering','Talk to the hosts about meals, kitchen access and spaces to gather. Confirm what is included in your booking.'),('Outdoors & quiet corners','Ask about garden and terrace access, and whether studio space or a cave visit can be arranged during your stay.')]))
pages['stay']=('Stay',section('SHORT STAYS · RESIDENCIES · WHOLE HOUSE','Stay for a moment.<br>Settle into a rhythm.','Choose a short mountain escape or enquire about a longer creative stay. Current prices, availability, fees and cancellation terms are shown on Airbnb.')+cards([('A short escape','A few days to walk, read and enjoy the mountain setting. Check the current minimum stay and room arrangements on Airbnb.'),('7–28 day residencies','Bring your writing, art, research or architectural curiosity. Enquire about space, connectivity and longer-stay pricing before committing.'),('The whole house','Time together with family or a small group. Confirm guest capacity, sleeping arrangements and exclusive-use terms with the hosts.')])+section('PLAN WITH CONFIDENCE','Know what is included.','Before paying, confirm meals, kitchen use, linen, bathrooms, hot water, connectivity, luggage assistance and transport. Your final quote should clearly list inclusions and any additional charges.'))
pages['retreats']=('Retreats & Residencies',section('A QUIET SETTING FOR SHARED PURPOSE','Gather with intention.','Bring an idea for a small retreat: yoga, meditation, art, writing, natural architecture, leadership or research. Dates, spaces, group size and facilitation are agreed individually.')+cards([('Tell us your intention','Share the kind of retreat you are planning, preferred dates, group size and what the group needs.'),('Shape it around the place','Discuss the walking approach, sleeping arrangements, food and appropriate spaces for your sessions.'),('Agree the details','Receive a tailored proposal from the hosts before making a booking. Activities and workshops depend on availability.')])+'''<section class="form-section wrap"><h2>Start a retreat conversation.</h2><p>Prepare your enquiry in your email app, then review and send it to the hosts.</p><form id="enquiry"><div class="fields"><label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Preferred dates<input name="dates" required placeholder="For example, 12–19 November"></label><label>Group size<input name="guests" type="number" min="1" max="100" required></label></div><label>What would you like to create?<textarea name="message" rows="4" required maxlength="3000"></textarea></label><button class="button" type="submit">Prepare enquiry email ↗</button><p id="form-status" role="status"></p><p>Prefer to speak? Call <a href="tel:+919899631375">+91 98996 31375</a>.</p></form></section>''')
pages['hemp']=('Build With Hemp',section('A LIVING LABORATORY','The architecture<br>is the experience.','Hempcrete and hemp-lime plaster sit alongside stone, timber and natural finishes. The house offers a place to look closely at materials and how they come together.')+f'<div class="wide wrap">{photo("hemp","Hempcrete natural building activity")}</div>'+cards([('Hemp & lime','See the building material and finishes in context. Ask about the construction process and the choices behind the walls.'),('Stone, timber & air','Explore the relationship between local materials, openings and natural ventilation.'),('Sun & rain','Rooftop solar panels and rainwater harvesting are part of the house’s approach to everyday resource use.')])+section('LEARN THROUGH PLACE','Curious about building with hemp?','Enquire about natural-building visits, workshops and the GoHemp connection. Ask the hosts for current opportunities, dates, fees and technical contacts; no scheduled programme is guaranteed.')+f'<div class="wrap">{link("mailto:himalayanhempecostay@gmail.com?subject=Hemp%20building%20enquiry","Ask about hemp building ↗","text-link")}</div>')
pages['story']=('Our Story',section('ROOTED IN PLACE. OPEN TO THE FUTURE.','An ancestral home.<br>A new chapter.','Gaurav and Namrata’s vision brings staying, creating and learning into the same conversation. The ancestral home and its reconstruction are at the heart of a quieter approach to Himalayan hospitality.')+f'<section class="split wrap">{photo("house","Stone and lime exterior of the house")}<div class="copy"><h2>A house that asks<br>a different question.</h2><p>How can a home welcome people while staying connected to its landscape, its materials and village life? Here, hemp-based construction becomes part of that exploration.</p><p>Visit with curiosity. Ask about the reconstruction journey, the people behind it and the lessons the house continues to offer.</p></div></section>')
pages['visit']=('Before You Come',section('A LITTLE PREPARATION MAKES SPACE FOR REST','The last stretch<br>is on foot.','This is a remote village stay. Allow around an hour for the walk and confirm the exact roadhead, meeting point and route before travelling. Timing varies with route, weather and pace.')+cards([('01 · Roadhead','Ask the hosts to confirm the approach to Faldakot Malla and onward travel from Rishikesh for your arrival date.'),('02 · Trail & village','Wear shoes with grip, pack lightly and plan to arrive in daylight. Confirm luggage support if you need it.'),('03 · Hemp house','Bring essentials before leaving town: shops nearby are limited. Settle into the quieter pace of village life.')])+'''<section class="faq wrap"><h2>Good to know before booking.</h2><details open><summary>Walking access & mobility</summary><p>Access requires a mountain walk. Discuss terrain, steps, mobility needs and luggage with the hosts before booking; do not assume vehicle access to the house.</p></details><details><summary>Weather & what to pack</summary><p>Check the forecast shortly before travel. Bring layers, walking shoes, rain protection, a torch and your everyday essentials. Ask about trail conditions during rain.</p></details><details><summary>Medical needs & emergency access</summary><p>Discuss any access requirements and the nearest available medical services with the hosts. Bring personal medicines and confirm an emergency transport plan before arrival.</p></details><details><summary>Connectivity, meals & facilities</summary><p>Confirm mobile coverage, Wi-Fi, power availability, hot water, dietary needs and meal arrangements for your dates, especially if planning to work remotely.</p></details><details><summary>House rules & cancellations</summary><p>Respect quiet hours, neighbours and shared spaces. Alcohol consumption, loud music and disruptive noise are not permitted. Please honour the quiet rhythm and traditions of our village. Confirm other house policies and cancellation terms before booking.</p></details></section>''')
pages['']=('A quiet Himalayan escape', (Path(__file__).parent/'home.html').read_text(encoding='utf-8'))
gallery='<section class="room-gallery wrap"><figure>'+photo('malla','Malla bedroom with natural plaster, wooden windows and twin beds')+'<figcaption>Malla · Light, texture & quiet</figcaption></figure><figure>'+photo('talla','Traditional stone hearth and timber staircase inside the house')+'<figcaption>The house · Crafted by hand</figcaption></figure></section>'
for key in ['house','stay']:
    pages[key]=(pages[key][0],gallery+pages[key][1])

from html import escape
assets=json.loads((Path(__file__).parent/'images.json').read_text(encoding='utf-8-sig'))
groups=[('House & landscape','gallery'),('Rooms & interiors','tariff'),('Experiences','activities'),('Around the region','sightseen'),('Guest reviews from our original website','testimonials')]
photos=''
for heading,folder in groups:
    entries=[v for v in assets if '/'+folder+'/' in v and (root/'original'/v).is_file()]
    photos+='<section class="gallery-section wrap"><h2>'+heading+'</h2><div class="photo-grid">'
    for v in entries:
        label=Path(v).stem.replace('-',' ').replace('_',' ').title()
        photos+='<figure><img loading="lazy" src="/original/'+escape(v)+'" alt="'+escape(heading+' — '+label)+'"><figcaption>'+escape(label)+'</figcaption></figure>'
    photos+='</div></section>'
pages['gallery']=('Gallery',section('REAL PLACES. REAL MOMENTS.','A closer look.','Explore photographs from our original website. Select any image to view it full size.')+photos)
note='<section class="village-note wrap"><p class="eyebrow">IN THE SPIRIT OF OUR VILLAGE</p><h2>A quiet place, shared with care.</h2><p>To honour the values of our village and preserve its peaceful atmosphere, alcohol consumption, loud music and disruptive noise are not permitted. We warmly invite you to enjoy gentle conversations, nature’s sounds and the unhurried rhythm of mountain life.</p></section>'
footer='<footer class="site-footer"><div class="footer-grid"><div><a class="brand footer-brand" href="/"><img class="site-logo" src="/original/img/logo.png" alt="Himalayan Hemp Eco Stay logo"><span>HIMALAYAN HEMP<br><small>ECO STAY</small></span></a><p>A hemp home in the Himalayas.<br>For staying, creating and reconnecting.</p><p>Faldakot Malla Village, PO Binak<br>Yamkeshwar, Pauri Garhwal<br>Uttarakhand 246121, India</p></div><div><h3>Explore</h3><a href="/house/">The house</a><a href="/stay/">Stays & residencies</a><a href="/retreats/">Host a retreat</a><a href="/hemp/">Build with hemp</a><a href="/story/">Our story</a><a href="/gallery/">Photo gallery</a></div><div><h3>Plan your visit</h3><a href="/visit/">Getting here & house guidelines</a><a href="https://www.airbnb.co.in/rooms/30969567">Availability & booking</a><a href="tel:+919899631375">+91 98996 31375</a><a href="tel:+919711216977">+91 97112 16977</a><a href="mailto:himalayanhempecostay@gmail.com">himalayanhempecostay@gmail.com</a></div><div><h3>Follow us</h3><p>Stories from the house and life in the hills.</p><a href="https://instagram.com/himalayanhempecostays" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.facebook.com/himalayanhempecovillage" target="_blank" rel="noopener">Facebook ↗</a><a href="https://wa.me/919899631375" target="_blank" rel="noopener">WhatsApp ↗</a></div></div><div class="footer-bottom"><span>© 2026 Himalayan Hemp Eco Stay</span><span>Respect the village. Leave the mountains as you found them.</span></div></footer>'

exec((Path(__file__).parent/'premium.py').read_text(encoding='utf-8'))
exec((Path(__file__).parent/'calm.py').read_text(encoding='utf-8'))
exec((Path(__file__).parent/'refinements.py').read_text(encoding='utf-8'))
for slug,(title,body) in pages.items():
    dest=root/slug; dest.mkdir(parents=True,exist_ok=True)
    menu=''.join(f'<a href="/{s}/"'+(' aria-current="page"' if s==slug else '')+f'>{t}</a>' for s,t in nav)
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} | Himalayan Hemp Eco Stay</title><meta name="description" content="{title}. A hemp home in Faldakot Malla, Uttarakhand, for slow stays, creative residencies and natural-building discovery."><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/premium.css"><link rel="stylesheet" href="/calm.css"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' fill='%232a332b'/%3E%3Ctext x='6' y='29' font-size='27' fill='%23eee7d9'%3EH%3C/text%3E%3C/svg%3E"><script src="/main.js" defer></script><script src="/weather.js" defer></script></head><body class="{'home' if not slug else 'inner'}"><a class="skip" href="#main">Skip to content</a><header><a class="brand header-brand" href="/" aria-label="Himalayan Hemp Eco Stay home"><img class="site-logo" src="/original/img/logo.png" alt="Himalayan Hemp Eco Stay"><span class="brand-name">HIMALAYAN HEMP<small>ECO STAY</small></span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation"><span class="menu-icon" aria-hidden="true"><i></i><i></i></span></button><nav id="navigation">{menu}</nav>{link(airbnb,'Book your stay ↗','nav-book')}</header><main id="main">{body}{note}{booking}</main>{footer}<aside class="contact" aria-label="Contact the hosts"><a href="https://wa.me/919899631375" target="_blank" rel="noopener">WhatsApp ↗</a><a href="tel:+919899631375">Call</a></aside></body></html>'''
    (dest/'index.html').write_text(html,encoding='utf-8')
print(f'Built {len(pages)} pages')
