# Hemp living positioning. Proposed facilities are explicitly marked as planned.
nav=[('stay','Stay'),('experience','Experience Hemp'),('hemp','Build With Hemp'),('retreats','Workshops & Retreats'),('story','Our Story'),('visit','Before You Come'),('gallery','Gallery')]
def enquiry_link(message,label):return link(enquire(message),label)
segments='''<section class="hemp-paths wrap" id="choose-experience"><div class="section-heading"><div><p class="eyebrow">THREE WAYS TO BELONG</p><h2>Come curious.<br>Stay your own way.</h2></div><p>A quiet home for travellers,<br>future builders and hands-on learners.</p></div><div class="hemp-path-grid"><article><span class="eyebrow">01 · PROSPECTIVE BUILDERS</span><h3>Live Before<br>You Build.</h3><p>A 2–3 night trial stay to experience hempcrete rooms, notice their everyday comfort and discuss the questions behind your own project.</p><a class="text-link" href="/hemp/#builder-stay">Explore the builder stay →</a></article><article><span class="eyebrow">02 · ECO-TRAVELLERS</span><h3>Stay Close<br>to Nature.</h3><p>Slow mornings, mountain light and a home made with natural materials. Discover the hemp story at your own pace; activities are optional.</p><a class="text-link" href="/stay/">Find your quiet stay →</a></article><article><span class="eyebrow">03 · RESEARCHERS &amp; LEARNERS</span><h3>Learn<br>With Hemp.</h3><p>Discuss a focused learning visit, workshop or residency around hemp materials, natural building and the journey from plant to everyday use.</p><a class="text-link" href="/retreats/#learning">Explore learning visits →</a></article></div></section>'''
vision='''<section class="hemp-vision wrap"><div><p class="eyebrow">FROM PLANT TO PLACE</p><h2>A home today.<br>A living showcase<br>taking shape.</h2><p>Our ancestral property brings hemp-based architecture and Himalayan village life together. We are developing an integrated hemp farm and immersive living experience around the home.</p><a class="text-link" href="/experience/">Discover the next chapter →</a></div><div class="hemp-stages"><article><span class="stage-label">EXPERIENCE TODAY</span><h3>Live within the material</h3><p>Stay in genuine hempcrete rooms and explore the house’s natural finishes with the hosts, by arrangement.</p></article><article><span class="stage-label">PLANNED · SEASONAL</span><h3>A small cultivation patch</h3><p>We plan to grow a small on-site patch under our cultivation licence. Hosted field walks will depend on planting, the season and visitor access being ready.</p></article><article><span class="stage-label">PLANNED</span><h3>Hemp Experience Center</h3><p>A dedicated room for raw materials, wall-section samples, construction stories and finished goods. Opening details will be shared when the space is ready.</p></article></div></section>'''
home=pages[''][1]
home=home.replace('Stay a while.<br>Come back to <em>calm.</em>','A Hemp Home.<br>A Living <em>Experience.</em>').replace('AN UNHURRIED HIMALAYAN STAY','STAY · DISCOVER · LEARN').replace('A hemp home in the Himalayas.<br>For slow mornings, quiet days and longer stays.','Come for the calm. Discover the material.<br>Experience another way of living.').replace('href="/house/">Explore the house','href="/experience/">Experience hemp')
home=home.replace('Welcome to a village home in the hills of Uttarakhand, where natural materials, thoughtful spaces and a slower rhythm make room for what matters.','Welcome to an ancestral hemp home in Uttarakhand. Stay within the material, meet the ideas behind the walls, and discover a slower rhythm rooted in village life.')
home=home.replace('<section class="editorial wrap">',segments+'<section class="editorial wrap">').replace('<section class="arrival wrap">',vision+'<section class="arrival wrap">')
pages['']=('A Hemp Home. A Living Experience.',home)
pages['experience']=('Experience Hemp',section('AN INTEGRATED HEMP FARM & IMMERSIVE LIVING EXPERIENCE','From the plant.<br>To the walls.<br>To the way we live.','Discover hemp through a place you can inhabit: an ancestral Himalayan home where materials, everyday comfort and village life become part of the same story.')+f'<div class="wide wrap"><img src="/assets/quiet-exterior.webp" alt="Stone and natural materials of the ancestral Himalayan home" loading="lazy"></div>'+vision+segments+'''<section class="faq wrap"><h2>Curiosity, at your own pace.</h2><details open><summary>What can I experience now?</summary><p>Book a stay in the house and ask the hosts to arrange a conversation about its hempcrete construction and natural materials. Agree any guided time, fees and inclusions before booking.</p></details><details><summary>Are farm walks and the Experience Center open?</summary><p>They are part of our next chapter and are not yet offered as confirmed visitor facilities. Ask about progress and seasonal opportunities when planning your dates.</p></details><details><summary>Do I need to join activities?</summary><p>No. Quiet leisure stays remain at the heart of the home. You can simply enjoy the mountains, read and rest. Learning sessions and group activities are arranged separately.</p></details></section>''')
builder='''<section class="builder-stay wrap" id="builder-stay"><p class="eyebrow">2–3 NIGHTS · BY ARRANGEMENT</p><h2>Live Before You Build.</h2><p class="lead">Before you choose a material for your own home, spend a little time living with it.</p><div class="hemp-path-grid"><article><span class="eyebrow">ARRIVE &amp; OBSERVE</span><h3>Feel the room.</h3><p>Spend a day and night in the house. Notice the light, ventilation, surfaces and your own sense of comfort in the season you visit.</p></article><article><span class="eyebrow">LOOK CLOSER</span><h3>Ask better questions.</h3><p>Arrange a materials conversation with the hosts: construction choices, finishes, maintenance and what they would approach differently.</p></article><article><span class="eyebrow">TAKE IT FORWARD</span><h3>Shape your next step.</h3><p>Discuss your location, project stage and priorities. Ask about the GoHemp connection and appropriate technical contacts for further advice.</p></article></div><p>Share your dates and project brief for a tailored proposal. Accommodation, meals, guided time and any consultation charges will be confirmed individually.</p>'''+enquiry_link('Hello, I am interested in a 2–3 night Live Before You Build stay. My preferred dates, guest count, project location and project stage are:','Enquire about a builder stay ↗')+'''<p class="small-print">A trial stay offers first-hand observations, not a performance guarantee. Comfort varies with weather, design and use; project-specific construction advice requires a separate assessment.</p></section>'''
pages['hemp']=(pages['hemp'][0],builder+pages['hemp'][1])
pages['stay']=(pages['stay'][0],section('QUIET HOSPITALITY, WITH ROOM FOR CURIOSITY','Stay Close to Nature.','Choose a restful mountain stay, a 2–3 night builder visit or a longer creative residency. Discover the house’s hemp story if you wish; there is no requirement to join an activity.')+pages['stay'][1])
learning='''<section class="learning wrap" id="learning"><p class="eyebrow">RESEARCHERS · MAKERS · CURIOUS MINDS</p><h2>Learn With Hemp.</h2><p>Bring a question, a research focus or an idea for a small group. We are developing focused sessions around natural materials and everyday uses of hemp.</p><div class="hemp-path-grid"><article><h3>Natural building</h3><p>Discuss a materials demonstration or introduction to hempcrete and finishes, with scope and facilitation agreed in advance.</p></article><article><h3>Farm to material</h3><p>Future seasonal sessions may follow cultivation and processing as the on-site patch develops. These activities are not currently guaranteed.</p></article><article><h3>Make &amp; discover</h3><p>Register interest in proposed hemp-soap or hemp-food sessions. Each session will be announced only once its facilitator, materials and arrangements are confirmed.</p></article></div><p class="small-print">No fixed workshop calendar is open yet. Dates, facilitator, group size, materials, fees and inclusions must be confirmed before payment. Research visits require an agreed scope; group sessions are planned around the quiet of the house and village.</p>'''+enquiry_link('Hello, I would like to discuss a Learn With Hemp visit. My topic, dates, group size and learning goals are:','Discuss a learning visit ↗')+'</section>'
body=pages['retreats'][1]
body=body.replace('START A RETREAT CONVERSATION','PLAN A WORKSHOP OR RETREAT').replace('Start a retreat conversation.','Plan a workshop or retreat.').replace('<option>Architecture & natural building</option>','<option>Architecture & natural building</option><option>Builder trial stay</option><option>Hemp materials workshop</option><option>Research residency</option><option>Future farm / soap / food session</option>')
pages['retreats']=('Workshops & Retreats',learning+body)
pages['story']=(pages['story'][0],pages['story'][1]+section('THE NEXT CHAPTER','An ancestral home.<br>A living hemp story.','Gaurav and Namrata’s next chapter connects the home with a small planned cultivation patch and a dedicated Hemp Experience Center. The intention is to make hemp tangible—from plant and material to the experience of living with it—while respecting the calm and traditions of the village.'))
booking=booking.replace('Choose your dates on Airbnb, or speak with us about a longer stay.','Book a peaceful stay, or speak with us about a builder visit, learning experience or longer residency.').replace('Plan a retreat','Plan a learning visit')
footer=footer.replace('A hemp home in the Himalayas.<br>For staying, creating and reconnecting.','A Hemp Home. A Living Experience.<br>Stay, discover and learn in the Himalayas.').replace('<a href="/hemp/">Build with hemp</a>','<a href="/experience/">Experience hemp</a><a href="/hemp/">Live Before You Build</a>').replace('>Host a retreat</a>','>Workshops &amp; retreats</a>')
