# Verified sources and the September 2026 refinements.
from html import escape
pin='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 22s8-8 8-14a8 8 0 1 0-16 0c0 6 8 14 8 14Z"/><circle cx="12" cy="8" r="2.5"/></svg>'
sunrise='''<section class="sunrise-story"><img loading="lazy" src="/original/img/gallery/gal11.jpg" alt="An orange sunset above the Himalayan hills"><div><p class="eyebrow">FIRST LIGHT. LAST GLOW.</p><h2>Two golden moments.<br>One place to slow down.</h2><p>Wake to sunrise over the hills. Stay for the quiet glow of sunset.<br>From our mountain home, there is time for both.</p><a href="/stay/#long-stay" class="button">Stay for another sunrise ↗</a></div></section>'''
attractions=[(12,'Camping','camping.jpeg','Time outdoors among the hills. Ask the hosts about local camping arrangements.','OUTDOORS'),(15,'Neelkanth Mahadev','neelkanth-mahadev.jpeg','A temple visit in the surrounding hills. Plan the journey with the hosts.','TEMPLE'),(18,'Bungee jumping','bungee.jpeg','An adventurous outing in the wider Rishikesh region. Book with the operator.','ADVENTURE'),(20,'Jhilmil Gufa','jhilmil-cave.jpeg','A cave and a quieter excursion into the surrounding landscape.','CAVE'),(20,'Yamkeshwar Mahadev','yumkeshwar.jpeg','Discover a temple rooted in the traditions of this region.','TEMPLE'),(22,'Ram Jhula, Rishikesh','ramjhula.jpeg','Make time for the riverfront and the atmosphere of Rishikesh.','RIVERFRONT'),(46,'Mahafgarh Temple','mahafgarh.png','A longer outing to a hilltop temple. Allow time for the journey.','TEMPLE')]
nearby='<section class="nearby wrap" id="nearby"><div class="section-heading"><div><p class="eyebrow">EXPLORE AT YOUR OWN PACE</p><h2>A little further<br>into the hills.</h2></div><p>Nearby attractions,<br>ordered by approximate distance.</p></div><div class="attraction-grid">'
for km,name,file,desc,kind in attractions:
    maps='https://www.google.com/maps/search/?api=1&amp;query='+quote(name+' Uttarakhand')
    nearby+=f'<article class="attraction-card" data-distance="{km}"><img loading="lazy" src="/original/img/sightseen/{file}" alt="{escape(name)}"><div><h3>{pin}{escape(name)}</h3><p>{desc}</p><div class="attraction-meta"><span>{pin}≈ {km} KM</span><span>{kind}</span><a href="{maps}" target="_blank" rel="noopener" aria-label="View {escape(name)} on Google Maps">Map ↗</a></div></div></article>'
nearby+='</div><p class="small-print">Distances are approximate figures from our <a href="https://www.himalayanhempecostay.in/#sightseen" target="_blank" rel="noopener">original website</a>, not live route measurements. The walk to the roadhead is additional; confirm routes, access and travel times with the hosts.</p><p class="small-print">Other outings listed on our original website: Neergarh Waterfall ≈ 21 km · River rafting ≈ 24 km. Ask about conditions and operators before planning.</p></section>'
google_url='https://www.google.com/travel/hotels/entity/ChkIsL-t7JH69KYyGg0vZy8xMXNta3hxM3RiEAE/reviews'
google_reviews=[('Krishanu Sanyal','Was lovely to meet Gaurav and Namrata with exceptional hospitality.','100902485950736727569'),('Kateřina Payerová','Beautiful views of the mountains, sunrises and sunsets.','104629812229678253932'),('Ashok Mahindroo','The food was outstanding.','111834788083754060791')]
google_section=f'<section class="google-reviews wrap" id="google-reviews"><div class="section-heading"><div><p class="eyebrow">GUESTS, IN THEIR OWN WORDS</p><h2>Small stays.<br>Lasting memories.</h2></div><div class="google-rating"><span>Google reviews</span><strong>4.9 <small>/ 5</small></strong><p>81 reviews · Checked 30 September 2026</p><a href="{google_url}" target="_blank" rel="noopener">Read all reviews on Google ↗</a></div></div><div class="review-cards">'
for name,quote_text,profile in google_reviews:
    google_section+=f'<article><p class="review-stars" aria-label="5 out of 5 stars">★★★★★</p><blockquote>“{quote_text}”</blockquote><a href="https://www.google.com/maps/contrib/{profile}" target="_blank" rel="noopener">{name}</a><p class="small-print">Google review · Selected excerpt</p></article>'
google_section+='</div><p class="small-print">A snapshot of Google reviews, not a live feed. <a href="/reviews/#guestbook-archive">Explore all 11 handwritten guestbook notes →</a></p></section>'
compare='''<section class="room-compare wrap"><p class="eyebrow">FIND YOUR QUIET CORNER</p><h2>Two rooms.<br>The same slower rhythm.</h2><div class="comparison-grid"><article><h3>Talla</h3><p>Warm bedroom colours, stone-and-timber details and an attached bathroom.</p><a href="/stay/#room-photographs" class="text-link">See Talla photographs →</a></article><article><h3>Malla</h3><p>Twin beds, timber windows and natural finishes. Confirm bathroom arrangements with the hosts.</p><a href="/stay/#room-photographs" class="text-link">See Malla photographs →</a></article></div><details><summary>Good to know before you choose</summary><p>Share your dates, guest count and preferred room. Confirm your quote, meals, hot water, connectivity, arrival support and cancellation terms before booking.</p></details></section>'''
home=pages[''][1]
home=re.sub(r'<section class="landscape-feature">.*?</section>',sunrise,home,flags=re.S)
home=re.sub(r'<section class="guestbook wrap">.*?</section>',google_section,home,flags=re.S)
home=home.replace(season,nearby+season)
# Avoid repeating the same yoga scene in the homepage room introduction.
home=home.replace('<div class="editorial-main"><img loading="lazy" src="/assets/quiet-yoga.png" alt="A traditional interior for quiet moments">','<div class="editorial-main"><img loading="lazy" src="/assets/malla.jpg" alt="Malla bedroom with twin beds and timber windows">')
pages['']=(pages[''][0],home)
pages['visit']=(pages['visit'][0],pages['visit'][1]+nearby)
pages['stay']=(pages['stay'][0],pages['stay'][1].replace('<section class="stay-rooms wrap">','<section class="stay-rooms wrap" id="room-photographs">')+compare)
pages['reviews']=(pages['reviews'][0],google_section+pages['reviews'][1])
footer=footer.replace('<a href="/reviews/">Guest stories</a>','<a href="/reviews/">Google reviews &amp; guestbook</a>')
